feat dataManipulation
class-dojo/backend pull request #25
Opened 2022-05-10 11:56 UTC by Fav8

this will implement the dataManipulation function inside the SentimentModel and the faceAnalysis interface

2022-05-10 12:46 UTC, tinazhouhui requested changes

2022-05-10 12:46 UTC, tinazhouhui commented on src/models/helpers.ts
> +import { IFaceDetails } from './interface';
quick question, do we need this file at all? I feel like removeuseless props will probably live in rekkognition model and calculate the scores should live inside the sentiment model no?

2022-05-10 13:04 UTC, tinazhouhui commented on src/models/helpers.ts
> +import { IFaceDetails } from './interface';
up to you :) technically speaking the role of the sentiment model is exactly what you just wrote tho - the model that takes care of the data :)

2022-05-10 14:43 UTC, Fav8 commented
EDIT: implementation of th efull datamanipulation flow, including the mock request to aws reckon.
only thing missing is the isImportant attribute to each frame in the frameinfo array because I need to talk with filo and the rest of you guys about it.

2022-05-10 15:15 UTC, tinazhouhui commented on src/models/RekognitionModel.ts
> +    return mockResponse;
just to make sure that I understand, whatever image we pass in we get the first mock response, correct?

2022-05-11 07:30 UTC, merged

2022-05-11 07:33 UTC, Fav8 commented
merged, closing